####################################
# 포트 및 프로젝트 명칭 설정
####################################
server:
  port: 80                    # 포트 설정
  servlet:
    charset: UTF-8            # 문자 인코딩 설정
    enabled: true             # 서블릿 활성화

spring:
  banner:
    location: banner/banner.txt # 배너 설정
  application:
    name: MyStory               # 프로젝트명 설정

  ####################################
  # 데이터베이스 설정
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mystory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    #    url: jdbc:mysql://supporty.synology.me:3006?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 992149

  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create    # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포멧 처리해서 보이기
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

####################################
# 로그 정보 설정
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # 물음표에 바인드 파라미터 출력

####################################
# 카카오 로그인 정보 설정
####################################
kakao:
  client:
    id: 772424d6f9f12c0080919dba87fcd137
    secret: TeQNfhDJN2T1IrCbylsnxCXZNtBvVWMr
  redirect:
    url: http://localhost/login/kakao

####################################
# ChatGPT API 설정
####################################
chatgpt:
  api-key: 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